# Generated by Django 3.0.8 on 2020-08-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tireoncar',
            unique_together={('car', 'tire', 'staff')},
        ),
    ]
