# Generated by Django 3.0.8 on 2020-08-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Done'), (0, 'Waiting')], default=0),
        ),
    ]
